import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source = fs.readFileSync('worker/src/metrics.js', 'utf8');
const {metrics} = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
let writes = [], limited = false;
const DB = {prepare(sql) { return {bind(...args) {return {async first() {return limited ? null : {count:1}}, async run(){writes.push(args)}}}}}};
const req = (body, headers={}, method='POST') => new Request('https://threeohfivestudios.com/api/events', {method,headers:{Origin:'https://threeohfivestudios.com','Content-Type':'application/json',...headers},...(method==='POST'?{body:JSON.stringify(body)}:{})});
const good = {event:'live_click',scene:'website',project:'aero'};
assert.equal((await metrics(req(good), {DB})).status,204);
assert.deepEqual(writes[0].slice(1),['website','live_click','aero']);
for (const bad of [{...good,project:'unknown'}, {...good,scene:'unknown'}, {event:'page_view',scene:'temple',project:'aero'}, null]) assert.equal((await metrics(req(bad),{DB})).status,400);
assert.equal((await metrics(req(good,{Origin:'https://evil.example'}),{DB})).status,403);
assert.equal((await metrics(req(good,{},'GET'),{DB})).status,405);
assert.equal((await metrics(req('x'.repeat(513)),{DB})).status,413);
assert.equal((await metrics(req(good,{DNT:'1'}),{DB})).status,204);
assert.equal(writes.length,1);
limited = true;
assert.equal((await metrics(req(good),{DB})).status,429);
assert.equal(writes.length,1);
const client = fs.readFileSync('assets/metrics.js','utf8');
function browser(path='/portfolio/', opt={}) {
 const events={}, sent=[], storage=new Map();
 const location=new URL('https://threeohfivestudios.com'+path);
 const document={visibilityState:'visible',addEventListener:(name,fn)=>events[name]=fn};
 const navigator={sendBeacon:(url,body)=>{sent.push(body);return true},...opt};
 const context={location,document,navigator,window:{},sessionStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},Blob,URL,Set};
 vm.runInNewContext(client,context);
 return {events,sent,context,async payloads(){return Promise.all(sent.map(async b=>JSON.parse(await b.text())))},click(href){events.click({isTrusted:true,type:'click',target:{closest:()=>({href:new URL(href,location).href,dataset:{}})}})}};
}
let b=browser();b.events.visibilitychange();assert.equal(b.sent.length,1);
b.context.window.portfolioMetric('project_view','aero');b.context.window.portfolioMetric('project_view','aero');assert.equal(b.sent.length,2);
b.context.document.visibilityState='hidden';b.context.window.portfolioMetric('contact_click');assert.equal(b.sent.length,2);
for(const opt of [{doNotTrack:'1'},{globalPrivacyControl:true},{webdriver:true}])assert.equal(browser('/portfolio/',opt).sent.length,0);
assert.equal(browser('/portfolio/pond-study.html').sent.length,0);
b=browser('/');b.click('/recent-work-autodex/');b.click('https://autodx.io/');b.click('/portfolio/');
assert.deepEqual((await b.payloads()).map(x=>x.event),['page_view','project_click','live_click','portfolio_click']);
assert.equal((await b.payloads())[1].project,'autodex');
console.log('Metrics client and endpoint checks passed');
const reportSource = fs.readFileSync('worker/src/report.js','utf8');
const {report} = await import('data:text/javascript;base64,'+Buffer.from(reportSource).toString('base64'));
let reads = 0;
const reportEnv = {METRICS_REPORT_KEY:'test-only',DB:{prepare(){return {bind(){return {async all(){reads++;return {results:[],meta:{rows_read:0}}}}}}}}};
assert.equal((await report(new Request('https://example.com/api/metrics-report'),reportEnv)).status,403);
assert.equal(reads,0);
const authorized = () => new Request('https://example.com/api/metrics-report',{headers:{Authorization:'Bearer test-only'}});
assert.equal((await report(authorized(),reportEnv)).status,200);
assert.equal((await report(authorized(),reportEnv)).status,200);
assert.equal(reads,1);
assert.equal((await report(authorized(),{})).status,403);
